title = "Bloom"
gitRepoUrl = "https://github.com/FrameBuffer-Studio/Bloom"

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

organizationName = "FrameBuffer Studio"
projectName = "Bloom"
url = "https://FrameBuffer-Studio.github.io"
baseUrl = "/Bloom"
tagline = "Blossom with possibilities."

[footer]
style = "dark"
copyright = "Copyright © 2026 FrameBuffer Studio"